### ISSUE TITLE
Right to left is this way <==

### ISSUE THREAD

**Issue by ltnKoen** [kberg/7wd-solo-fan#2]
Line 15:

`DROITE_A_GAUCHE = ['Droige à gauche ==>', 'Right to left ==>']`

should be:

`DROITE_A_GAUCHE = ['Droite à gauche <==', 'Right to left <==']`

(this fixes the sense of the arrow, as well as the typo "droige"/"droite")

**Comment by kberg** [comment]
Fixed.

**Comment by kberg** [comment]
Thanks!
